### ISSUE TITLE
Add support for standalone use

### ISSUE THREAD

**Issue by popovicieduard** [tnkemdilim/adonis-class-validator#1]
Is there a way to use this without having to use the `request.classValidate` ?

It would be nice to have a  `.validate` method or another way to validate things independent of the request.

```
// SignupPayload.ts
import { validate, schema, rules } from "@ioc:Adonis/ClassValidator";

class SignupPayload extends BaseValidator {
  @validate(schema.string({}, [rules.required(), rules.email()]), {
    required: "Field {{name}} is required.",
    email: "Invalid email address",
  })
  public email!: string;
}
```

```
// SignupController.ts
import { SignupPayload } from "App/Validators";
import { HttpContextContract } from "@ioc:Adonis/Core/HttpContext";

class SignupController {
  public async index({ request }: HttpContextContract) {
    const payload = await new SignupPayload(request.qs).validate(); // something like this

    const payload2 = await ClassValidaor.validate(SignupPayload, request.qs) // or something like this
  }
}
```

**Comment by toksdotdev** [comment]
Thanks a lot, @popovicieduard for the suggestion.

I've added support for it via #2, and it's currently available in version [`0.2.0`](https://github.com/tnkemdilim/adonis-class-validator/releases/tag/v0.2.0) (which I already published).

I also added a basic example to the readme [here](https://github.com/tnkemdilim/adonis-class-validator#standalone-validator).

Thanks once again.
